### ISSUE TITLE
Improve screen reader accessibility for Accordion element 

### ISSUE THREAD

**Issue by aknoxpcls** [KriesiMedia/Enfold-Feature-Requests#104]
Requesting that the accordion element be updated to align with accessible accordion design pattern as described here: https://www.w3.org/WAI/ARIA/apg/patterns/accordion/ (example: https://www.w3.org/WAI/ARIA/apg/patterns/accordion/examples/accordion/ ) 

Specific screen reader accessibility issues encountered with the accordion element in version 5.7.1: 

 - After expanding an accordion section using the enter key, if the content of the expanded panel is text only, the screen reader can’t access the expanded content.  

- After expanding an accordion section, if there is a focusable element within the expanded panel content, the screen reader can access that element, and then text content after that element can be read; however, text content within the expanded panel but above the focusable element is not always accessible (for instance if the text above is in a separate paragraph). 

 - When an accordion section header has focus, the screen reader reads the header text, but does not state if the section is open or closed, and includes meta information about the element that is not accurate (refers to each accordion section as a tab control with a single tab).  

(screen reader used is NVDA, available for free here: https://www.nvaccess.org/download/) 

Originally submitted as a support request here: https://kriesi.at/support/topic/accessibility-compliance-for-accordion-element/

**Comment by InoPlugs** [comment]
@aknoxpcls 

Thanks for suggesting this.

A solution will be added to Enfold 6.0
