### ISSUE TITLE
gradient color options

### ISSUE THREAD

**Issue by Janell** [KriesiMedia/Enfold-Feature-Requests#118]
When selecting colors for Theme options>General styling > Area background colors.
Make it possible to generate gradients from two or three colors.

**Comment by ip2C** [comment]
no please not.  We don´t need any features that will make the website sloder.

**Comment by Janell** [comment]
As it is currently, if you want a gradient color in your footer you have to use a large image which makes the website slower!! Just a simple color option would not slow down the website!

**Comment by ip2C** [comment]
Of course not an image.  In HTML you have to use CSS!  Like in my page:   https://ip2c.de

#footer { 
  background: linear-gradient(to bottom, #2b4056 0%, #111b22 100%);
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#2b4056', endColorstr='#111b22', GradientType=0);
}

**Comment by Janell** [comment]
The gradient color option is clearly already coded in the theme for other things like: content elements-buttons.  Seems like it could also just be added to background colors for Theme options>General styling > Area background colors.

**Comment by Janell** [comment]
@ip2C Thank you for your CSS suggestion. I just copied and pasted your code to the Quick CSS and edited the colors. This will do for now.
