### ISSUE TITLE
[Header] Sticky header on mobile

### ISSUE THREAD

**Issue by vatoyiit** [KriesiMedia/Enfold-Feature-Requests#17]
https://kriesi.at/support/topic/sticky-mobile-menu-6/

https://kriesi.at/documentation/enfold/header/#sticky-header-on-mobile

Deeper insight:

https://elad.medium.com/css-position-sticky-how-it-really-works-54cd01dc2d46

P.S.: See the original issue for more information.

**Comment by InoPlugs** [comment]
https://github.com/KriesiMedia/Enfold-Feature-Requests/issues/52
