### ISSUE TITLE
[Header] Missing Title Tag in the 

### ISSUE THREAD

**Issue by hibabino** [KriesiMedia/Enfold-Feature-Requests#51]
The H1 title is missing in every article title tag, how can I enable it?
https://spicycamping.com/wp-content/uploads/2023/05/截圖-2023-05-23-18.41.58.png

**Comment by vatoyiit** [comment]
@hibabino 
You can add the following code to the bottom of the functions.php file of your child theme (https://kriesi.at/documentation/enfold/child-theme/) to change heading to H1:
```
function my_avf_customize_heading_settings( array $args, $context, array $extra_args = array() )
{
	$args['heading'] = 'h1';
	return $args;
}
add_filter( 'avf_customize_heading_settings', 'my_avf_customize_heading_settings', 10, 3 );
```

If this isn't what you meant or have any other questions or issues, please start a thread on our support forum at https://kriesi.at/support.
