### ISSUE TITLE
[Request] Display posts only if the post is checked in all categories selected

### ISSUE THREAD

**Issue by cipher87** [KriesiMedia/Enfold-Feature-Requests#53]
Thread: https://kriesi.at/support/topic/display-posts-that-are-assigned-to-category1-and-category2/

User Description:
If the post is in category1 and not in category2 then don´t display the post.
If the post is not in category1 and in category2 then don´t display the post.
If the post is in category1 and in category2 then display the post.

**Comment by InoPlugs** [comment]
https://github.com/KriesiMedia/wp-themes/pull/4194
