### ISSUE TITLE
[Request] Exclude page IDs from ENFOLD's maintenance mode

### ISSUE THREAD

**Issue by beceha** [KriesiMedia/Enfold-Feature-Requests#54]
Thread:
https://kriesi.at/support/topic/maintenance-mode-exclude-page-ids/#post-1409318

Option to exclude certain page IDs from maintenance mode, like for example privacy page (GDPR)

**Comment by InoPlugs** [comment]
filter 'avf_exclude_maintenance_id' since 5.1

https://kriesi.at/support/topic/exclude-pages-from-maintenance/
