### ISSUE TITLE
How to disable the fancy & in font

### ISSUE THREAD

**Issue by moritzkoester** [KriesiMedia/Enfold-Feature-Requests#56]
Hi, 

when I am writing something as a headline and there is a &-sign in it - it is automatically transformed, how can I disable that? 

<img width="261" alt="Bildschirmfoto 2023-06-19 um 17 19 29" src="https://github.com/KriesiMedia/Enfold-Feature-Requests/assets/137089285/017c9679-f885-4210-be6f-d7a43a6f946e">

**Comment by vatoyiit** [comment]
@moritzkoester For now, you can add the following code to Enfold theme options > General Styling > Quick CSS field: 
```
#top .special_amp {
    font-family: sans-serif;
    font-size: inherit;
    font-style: inherit;
    font-weight: lighter;
    color: inherit;
}
```

We'll note this as a feature request. If you have any theme related questions, please start a thread on our support forum at https://kriesi.at/support

**Comment by moritzkoester** [comment]
Thank you!

**Comment by moritzkoester** [comment]
Thank you !
