### ISSUE TITLE
columns parallax effect – Speed less than 10%

### ISSUE THREAD

**Issue by BenjaminSpeedtsberg** [KriesiMedia/Enfold-Feature-Requests#62]
If the adjustment interval could be 1 or 2% instead of 10% that would be awesome. 10%+ i just too much parallax effect.

**Comment by InoPlugs** [comment]
@BenjaminSpeedtsberg 

I reduced it to 2% - should be a good compromiss not to make the selectbox too large.
Will be in 5.6.6.

If you still think it is too much let us know and we can add a filter so you can adjust it yourself as needed.

**Comment by BenjaminSpeedtsberg** [comment]
@InoPlugs Sounds great! Look forward to the next update! :-)

**Comment by ip2C** [comment]
HAve you ever looked what happened when it is more than 10%?  30 %+  It is just bad looking. Bad behaviour.    So 2,4,6,8,10, 12,14,16,20 and minus all that will be perfect

**Comment by BenjaminSpeedtsberg** [comment]
i agree with you @ip2C. So it's great that we can look into that change very soon!

**Comment by InoPlugs** [comment]
If you want to test it:

Replace "enfold\config-templatebuilder\avia-template-builder\php\base-classes\class-popup-templates-responsive.php"

with 

https://github.com/KriesiMedia/enfold-library/blob/master/temp_fixes/Enfold_5_6_5/config-templatebuilder/avia-template-builder/php/class-popup-templates-responsive.php

**Comment by BenjaminSpeedtsberg** [comment]
Thanks, I tried it, but I can't see the changes in Avia. 
<img width="749" alt="Skærmbillede 2023-08-02 kl  18 00 19" src="https://github.com/KriesiMedia/Enfold-Feature-Requests/assets/50696099/d6b15737-8904-4135-9fe3-f56af85d8dc3">

**Comment by InoPlugs** [comment]
@BenjaminSpeedtsberg 

Sorry, uploaded the old version. Please check again.

**Comment by BenjaminSpeedtsberg** [comment]
@InoPlugs 

Now it works, looks great, thanks! :-)

**Comment by InoPlugs** [comment]
@BenjaminSpeedtsberg 

Thanks for your feedback and your suggestion.

Enjoy the theme and have a great day.
