### ISSUE TITLE
[Request] Add a TikTok icon to Social Profiles

### ISSUE THREAD

**Issue by vatoyiit** [KriesiMedia/Enfold-Feature-Requests#67]
The TikTok icon is not available on https://fontello.com/. Is there any other way to add it to Enfold? 

Requested at https://themeforest.net/item/enfold-responsive-multipurpose-theme/4519990/comments?page=1&filter=all#comment_29834280

**Comment by InoPlugs** [comment]
https://github.com/KriesiMedia/wp-themes/pull/4235
