### ISSUE TITLE
[Request] Display an edit icon when hovering over the images inside Masonry Gallery element

### ISSUE THREAD

**Issue by vatoyiit** [KriesiMedia/Enfold-Feature-Requests#69]
Currently, there's no indicator on hover:
![Screenshot 2023-08-30 at 13 07 10](https://github.com/KriesiMedia/Enfold-Feature-Requests/assets/5331416/6e2cd0af-00b4-4dcc-848c-07d4e84375c4)

A user would like to display an edit icon on hover.

Thread: https://kriesi.at/support/topic/masonry-gallery-custom-icons/

**Comment by ip2C** [comment]
come on.  There are more necessary Issues then the need of 1 user
