### ISSUE TITLE
Update Twitter logo to X across site

### ISSUE THREAD

**Issue by broadeye** [KriesiMedia/Enfold-Feature-Requests#71]
It's been months - this needs sorting

**Comment by vatoyiit** [comment]
The base icons of Enfold are from Fontello ( https://fontello.com/ ) and the new Twitter X icon isn't available on Fontello yet. We will update the icon once it's available. 

For now, please refer to this post and add the icon manually: https://kriesi.at/documentation/enfold/social-share-buttons/#how-to-add-custom-social-icons-to-enfold-options.

**Comment by InoPlugs** [comment]
Planned for 5.6.7
