### ISSUE TITLE
Link to Mastodon Account

### ISSUE THREAD

**Issue by jze** [KriesiMedia/Enfold-Feature-Requests#79]
There are a variety of ways to link data capitalist services. However, it lacks the ability to link one's Mastodon account.

Ideally, the link to [verify the account](https://joinmastodon.org/verification) will be generated at the same time.

**Comment by vatoyiit** [comment]
Hey @jze just to clarify, you'd like us to add a Mastodon icon to the social profiles in the Enfold theme options. Is that correct?

**Comment by ip2C** [comment]
what is mastodon and is this usefull for a wide range of users?   I don´t think so.

**Comment by jze** [comment]
The icon is the most important thing. 

Additionally it would be nice if entering the Mastodon account handle would automatically add the `<a rel="me" href=""></a>` element for the account verification.

**Comment by jze** [comment]
> what is mastodon and is this usefull for a wide range of users? I don´t think so.

The German national government runs their own Mastodon server <https://social.bund.de> as well as several German federal states (e.g. <https://social.hessen.de>, <https://social.schleswig-holstein.de and others). Large media also have their own server, e.g. <https://ard.social> and <https://social.bbc> 

Wordpress itself is part of the Fediverse, of which Mastodon is a large part: <https://de.wordpress.org/plugins/activitypub/>

**Comment by ip2C** [comment]
Thanks for the answer.  I still not get it -  I don´t understand the internet anymore since a few months :D

**Comment by InoPlugs** [comment]
@jze 

Hi,

To clarify:

- We add "Mastodon" to the selectbox in Theme Options -> Social Profiles -> Social Icon
- In Social Icon URL you enter an url that links to your mastodon account e.g. https://your_account.domain

In Frontend along with the other icons:

- We render the "Mastodon" icon
- The link will be  `<a rel="me" href="https://your_account.domain">`
