### ISSUE TITLE
Header sticky anchor

### ISSUE THREAD

**Issue by emliron** [KriesiMedia/Enfold-Feature-Requests#81]
Hi,
 
I've noticed the following error on my sites, and on the support forum, when using Firefox on PC.
For example, if you open: https://kriesi.at/support/topic/offset-smooth-scroll-shrink-sticky-header/#post-1424700 in the search bar, the page scrolls too low.
This doesn't happen with Edge or Chrome.
On my own sites ( www.assopogo.net  and www.drangadz.fr)  there is no problem anymore if I disable the sticky header.
The advice given on the link doesn't work properly on my sites.
 
Kind regards
 
Emmanuel

**Comment by vatoyiit** [comment]
Hi @emliron,

We only accept feature requests here. If you'd like us to investigate the issue on your website, please start a thread on our support forum https://kriesi.at/support/forum/enfold/#new-post and send us temporary admin logins and a screen recording to show the issue.

**Comment by emliron** [comment]
Hello,
 
This isn't a problem on my site, but a theme, since it doesn't work on the Enfold forum itself (I run three sites that all use Enfold).
I would therefore like to point out that it is not possible to use the header sticker in Firefox, with the anchors working correctly. It's up to you to correct it or not!
Kind regards
