### ISSUE TITLE
[Request] File Download Element

### ISSUE THREAD

**Issue by eberhapa** [KriesiMedia/Enfold-Feature-Requests#82]
Hi,

Would be nice to get a File Download Element for text files, pdf, e.g. 
Further fields could be icon, title. Maybe do it as repeater field?

Thanks,
Patrick

**Comment by InoPlugs** [comment]
@eberhapa 

In next release 5.7 I added a simple solution for this to ALB button -> link setting toggle -> Download button. 

You can select either an uploaded file from media gallery or add a custom link to a file to download.
