### ISSUE TITLE
maintenance mode & footer page & 404 page options show "inactive" in page list

### ISSUE THREAD

**Issue by mgmason** [KriesiMedia/Enfold-Feature-Requests#83]
I understand that when the maintenance mode page or footer page or the 404 page options are disabled that on the page list a notice is shown next to these pages that the option is "inactive"
But many new users find this troubling and find it difficult to disable the message by activating each setting then select "select page" from the options, then deactivate the option, then save the theme settings.
Perhaps we should remove the "inactive" message to solve this confusion?
Thank You.

a few threads:
https://kriesi.at/support/topic/this-page-is-selected-to-be-displayed-as-maintenance-mode-page-but-is-not-active-2/
https://kriesi.at/support/topic/this-page-is-selected-to-be-displayed-as-maintenance-mode-page-but-is-not-active/
https://kriesi.at/support/topic/maintenance-mode-and-demo-pages-not-showing-up/
https://kriesi.at/support/topic/maintenance-mode-6/

**Comment by InoPlugs** [comment]
Added an info message in 5.6.9 to theme options
