### ISSUE TITLE
[Request] Order of LayerSliders (Avia Element)

### ISSUE THREAD

**Issue by martin-roessler** [KriesiMedia/Enfold-Feature-Requests#85]
Hey,
please could you implement an option, where user can modify the sorting of LayerSliders in the Avia-Element. When a website have an amound of LayerSliders, it would be useful to order by Slidername instead of date_c column.

**Comment by InoPlugs** [comment]
@martin-roessler 

I added filter 'avf_layerslider_order_by_select_alb' to ..\config-layerslider\config.php line 852ff - Enfold 6.0.1

A copy (based on 6.0) can be downloaded here if you want to test:

https://github.com/KriesiMedia/enfold-library/blob/master/temp_fixes/enfold_6_0/config-layerslider/config.php

**Comment by martin-roessler** [comment]
Thanks for implementing :)
