### ISSUE TITLE
Adding certified Cookie Management Protocol 

### ISSUE THREAD

**Issue by motomuis** [KriesiMedia/Enfold-Feature-Requests#88]
Google is demanding that we use certified CMP's if we want to use adverts. It would be nice if your cmp would be certified.

**Comment by vatoyiit** [comment]
@motomuis 
I'm afraid this is too advanced for our cookie management tool. If that's something you need, please use a dedicated third-party plugin, such as the Borlabs Cookie ( https://borlabs.io/borlabs-cookie/ )
