### ISSUE TITLE
Loading of mixed content

### ISSUE THREAD

**Issue by mfeindt** [KriesiMedia/Enfold-Feature-Requests#90]
Hi,

please change http to https in
enfold\framework\php\function-set-avia-frontend.php
on line 512

http://gmpg.org/xfn/11
to 
http**s**://gmpg.org/xfn/11

**Issue background**
The application loads pages over HTTPS that load other resources over unencrypted connections. An attacker suitably positioned to view a legitimate user's network traffic could record and monitor their interactions with these resources, which may indirectly disclose information about the user's activity on the application itself. Furthermore, an attacker able to modify traffic could alter these resources and potentially influence the application's appearance and behavior. Due to these concerns, users' web browsers may automatically display warnings and disable affected components of the page. As a result, this vulnerability currently has more of an impact on usability than security.

Best Regards

**Comment by InoPlugs** [comment]
@mfeindt 

Thank you for reporting this. Will be fixed in next release 5.6.10
