### ISSUE TITLE
Headline Element change size

### ISSUE THREAD

**Issue by eberhapa** [KriesiMedia/Enfold-Feature-Requests#93]
Now it is possible to set the tag (h1-h6) and set a fixed size for the heading.
It would be nice to be able to set a extra size by selecting h1-h6.

Now we are creating a new Enfold Element and we are adding a new dropdown for the size select.

In the end the output looks like (shortened for demonstration purpose) `<h1 class="h2"></h1>`. It's technically a h1 but with the size of a h2. It's better for styling because we are able to change the size via breakpoints.

**Comment by ip2C** [comment]
Sounds good.  In the past I made my own CSS by   h1  Class:  .is_h2   .is_h3   .is_h4   ....  THois would be better for a clerarer understanding and styling. 

Because I style my font with fluid clamp.

**Comment by InoPlugs** [comment]
@eberhapa  @ip2C 

I think this can already be done:

- You can set responsive font sizes in Option "Heading Font Sizes"
- You have "Custom CSS Class" option: lets say you use "custom-h1-h2"

then you can use the selector:

`.av-special-heading.custom-h1-h2 > h1{ font-size: xx; } `

and you can wrap this in breakpoints also.

Or am I missing or misunderstanding something ?

**Comment by eberhapa** [comment]
I can but my customers can't. A second dropdown for the class-size would be more convenient.

**Comment by InoPlugs** [comment]
@eberhapa @ip2C 

As there are not many requests  we use theme support 'avia_builder_add_heading_type_size_class' to add the dropdown.
Class strings are av-is-h1, av-is-h2, ......

Styling is not supported by theme.

If you want to test:

https://github.com/KriesiMedia/enfold-library/blob/master/temp_fixes/enfold_6_0/config-templatebuilder/avia-shortcodes/heading/heading.php

**Comment by ip2C** [comment]
Please ...  there are already way too much Entryforms and Dorms and checkboxes in the Layoutbuilder.  @eberhapa    Use custom CSS and tell your client how they can use <h2 class="is_h1">  ....    I do the same actually for a client. 

I don´t want that he set a Font with 60px because they don´t know about responsive / fluid Desigs

**Comment by eberhapa** [comment]
@ip2C like I said it‘s more convenient with a dropdown. I don‘t want my customers to set any classes.

@InoPlugs thanks, I will check tomorrow. Will be more interessing for people when the european accessibility act kicks in because we are already now getting a lot of feedback that the heading orders are not correct in the frontend.

**Comment by eberhapa** [comment]
@InoPlugs thanks, works nice

**Comment by eberhapa** [comment]
@InoPlugs could you set the class on .av-special-heading instead of .av-special-heading-tag because now we are not able to control the size of the subheading

**Comment by InoPlugs** [comment]
@eberhapa 

added additional class av-font-size-is-xx to container. 

Hope this helps.

To test:

https://github.com/KriesiMedia/enfold-library/blob/master/temp_fixes/Enfold_6_0_1/config-templatebuilder/avia-shortcodes/heading/heading.php

**Comment by eberhapa** [comment]
@InoPlugs perfect, thanks
