### ISSUE TITLE
[Request] File Upload to Form

### ISSUE THREAD

**Issue by caferkara** [KriesiMedia/Enfold-Feature-Requests#94]
Hi, I want to file upload option to form. When my customer fill the form with file I want to receive that. But right now Enfold theme does not have upload file option. I do not want to use different form plugins. That's why I hope Enfold developers can do this asap.

Thanks

**Comment by jfpayette** [comment]
I am having same request...

**Comment by InoPlugs** [comment]
What should happen with the uploaded file.

Too specific for a theme. There are contact form plugins which can handle this better.

**Comment by caferkara** [comment]
Too specific for the theme? I do not think so. For example, I created a career page. People must send their info from the form. Also, they must send their CV as pdf or jpg file. I want to do everything with the theme. Why should I install another plugin? Of course I know "contact us form 7" plugin is great. I do not think so it's too difficult for Enfold team. For example, also, I have Avada theme. They did it. When you use Avada theme, you do not need to use so many plugins. Because they did everything with the theme. I hope you understand what I mean.

**Comment by InoPlugs** [comment]
@caferkara 

I understand what you mean.

I digged into the topic and stumbled across the problem how to prevent upload of malware / spyware or other type of dangerous files. There is no browser support for that and only checking file type is not enough.

Another problem for a common solution necessary for a theme are settings of mail servers prohibiting or limiting attachments.

Having discussed it with Kriesi we decided not to implement it as there are a lot of good plugins that are specialised and optimized on that problem and provide security measurements.

**Comment by jfpayette** [comment]
It's unfortunate because it's the only feature missing from this theme; otherwise, it's perfect for me. 
To achieve my goal, I installed the **Contact Form 7** and **Drag and Drop Multiple File Upload - Contact Form 7** plugins. 
However, I would have preferred to use the Enfold contact form because it's more intuitive and user-friendly.
