### ISSUE TITLE
Option to decide if featured image got link or not on single post

### ISSUE THREAD

**Issue by GuenniWeb** [KriesiMedia/Enfold-Feature-Requests#97]
https://kriesi.at/support/topic/remove-featured-image-expand-in-posts/#post-1440910

if this is too complex to fullfil - a filter would be nice to have to hamper the building of link on the featured image.
see discussion on https://kriesi.at/support/topic/remove-featured-image-expand-in-posts/

**Comment by InoPlugs** [comment]
@GuenniWeb 

https://github.com/KriesiMedia/enfold-library/blob/master/temp_fixes/Enfold_5_7/includes/loop-index.php

added filter avf_post_ingnore_featured_image_link:

https://github.com/KriesiMedia/enfold-library/blob/master/actions%20and%20filters/Layout/avf_post_ingnore_featured_image_link.php

Should allow to remove links from all types of layout.

Can you please check.
Will be added to 5.7.1

**Comment by GuenniWeb** [comment]
thanks!!!
