### ISSUE TITLE
svg in media-library list-view

### ISSUE THREAD

**Issue by GuenniWeb** [KriesiMedia/Enfold-Feature-Requests#98]
add to avia-admin.css:

`.wp-admin #the-list .has-media-icon img[src*=".svg"] {
  width: 60px;
  height: auto;
}`

[https://kriesi.at/support/topic/preview-images-on-pages-post/#post-1440927](https://kriesi.at/support/topic/preview-images-on-pages-post/#post-1440927)

**Comment by InoPlugs** [comment]
@GuenniWeb 

Thanks. But had to be added to avia_global_admin.css.

Should be part of 5.7.1.
